name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.name-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.name-version }}
      - name: install modules 
        run: npm install --legacy-peer-deps
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: testing unit
        run: npm run test:unit